### ISSUE TITLE
About the loss the inconsistency between the loss function of the code and the paper

### ISSUE THREAD

**Issue by cjissmart** [hengruizhang98/CCA-SSG#1]
Congratulations on the great paper and on being accepted to NIPS! I have a problem with the loss function.
The code corresponding to the self-supervised learning loss function is on lines 75 and 88 of 'main.py'. The formulation of the code is as follows.
![image](https://user-images.githubusercontent.com/37531166/143823381-70a49476-50ed-42e5-a0f0-f841628e4456.png)
![image](https://user-images.githubusercontent.com/37531166/143823723-9bfe65a1-1bdf-4938-8b6f-2bd1cd378e9e.png)
However, the formulation in the paper should be:
![image](https://user-images.githubusercontent.com/37531166/143823988-548906f0-73f3-4478-9982-63da9b8cb689.png)
![image](https://user-images.githubusercontent.com/37531166/143824055-a91997b9-5f32-404c-88e2-c43e824c6c4e.png)
They are not consistent. Why is this the case?

**Comment by hengruizhang98** [comment]
Thanks for your interest in our work!
     These two implementations are equivalent. Note that Z is standardized
(0-mean and 1/\sqrt{N} variance), we have || Z_A ||_2^2 = || Z_B ||_2^2 =
1. And then L_Inv = || Z_A - Z_B ||_2^2 = || Z_A ||_2^2 + || Z_B ||_2^2  -
2 * Z_A^T Z_B = 2 - 2* Z_A^T Z_B, so we minimize Z_A^T * Z_B in the codes
instead.

cjissmart ***@***.***> 于2021年11月29日周一 上午1:17写道：

**Comment by hengruizhang98** [comment]
Thanks for your interest in our work! 
     These two implementations are equivalent. Note that Z is standardized (0-mean and 1/\sqrt{N} variance), we have || Z_A ||_2^2 = || Z_B ||_2^2 = D. And then L_Inv = || Z_A - Z_B ||_2^2 = || Z_A ||_2^2 + || Z_B ||_2^2  -  2 * Z_A^T Z_B = 2D - 2* Z_A^T Z_B, so we minimize Z_A^T * Z_B in the codes instead.

**Comment by cjissmart** [comment]
I find the reason in E.1 of Appendix.

**Comment by hengruizhang98** [comment]
Yes, we also explain that in the Appendix.

**Comment by cjissmart** [comment]
> 
Thanks for the reply !!!
