### ISSUE TITLE
Question about linear evaluation

### ISSUE THREAD

**Issue by THINK2TRY** [hengruizhang98/CCA-SSG#2]
Generally, only the validation set is used to help select the best_model during the training. So I wonder, is it appropriate to use `test_acc` to help select the `eval_acc`?
![image](https://user-images.githubusercontent.com/48679723/150087584-971ed31b-8eed-406d-a14a-330955bc2dd1.png)

**Comment by hengruizhang98** [comment]
Hi, thanks for your question. This might be inappropriate but actually it makes little difference to the final evaluation accuracy. Just make sure to use the same setting for all the comparing methods.

**Comment by THINK2TRY** [comment]
Thanks for your response. 
I try to reproduce the results after the modification. The results in Cora and Citeseer make little difference, but the performance in PubMed actually decreases. (~0.8091 for 20 random initialization).

**Comment by hengruizhang98** [comment]
Thanks again for pointing out this problem. We will update this result in the future version if possible. And as you can see, our method still beat other methods on PubMed dataset. Feel free to use your reproducing results if you would like to use our method as the baseline in the future.

Best

**Comment by THINK2TRY** [comment]
Thank you for your reply! And thanks for the excellent work!
