### ISSUE TITLE
The way of evaluation

### ISSUE THREAD

**Issue by liun-online** [hengruizhang98/CCA-SSG#3]
Hi, author ! Thanks for your code! But I have a puzzle about the evaluation. In 147~150 lines of main.py, you first decide if the new val_acc is bigger than original one. If this condition is satisfied, you then decide the test_acc in the same way. However, during the training of logreg, the test shouldn't be used in my opinion, while only validation is ok. Is there any problem?

**Comment by hengruizhang98** [comment]
See this issue #2

**Comment by liun-online** [comment]
ok
