### ISSUE TITLE
A question about correlation matrix

### ISSUE THREAD

**Issue by simon-hope** [hengruizhang98/CCA-SSG#4]
Hi Hengtui,

May I ask one question about your paper?

In Section F.1, you visualize the correlation matrix. However, I didn't find any formal definitions for the correlation matrix. Is it the same as the covariance matrix mentioned in Section 3.2?

Best regards,
Simon

**Comment by hengruizhang98** [comment]
Yes, the correlation is the same as the standardized covariance matrix (line 79 in main.py).

**Comment by simon-hope** [comment]
Thanks for your reply!
