### ISSUE TITLE
About 1/sqrt(N) std

### ISSUE THREAD

**Issue by SeongJinAhn** [hengruizhang98/CCA-SSG#5]
I'm very impressed by your works.
Thanks.

Is there any reason or insight that you normalize node representations with std 1/ sqrt(N) rather than 1?

Also, in my work, the result was fine when i normalize with setting std as you.
But i'm wondering about the reason.
If you have any insights or refetences, feel free to answer me.

Any small answer may be a huge pleasure.

**Comment by hengruizhang98** [comment]
Hi, thanks for your intereset of our paper. We normalize the embeddings with std 1/sqrt(N) to make sure the diagoal terms of its correlation matrix Z^T Z to be 1, and thus will convenience the computation of the objective function.

**Comment by SeongJinAhn** [comment]
Oh! that's reasonable.
Your comment and appendix help me to understand it broader.
Thank you for answer.
